### ISSUE TITLE
vite.config.ts intellisense error

### ISSUE THREAD

**Issue by Fractal-Tess** [bfanger/svelte-project-template#6]
They there,

When installing the template, and running the dev server, I'm getting this error:
![image](https://user-images.githubusercontent.com/75957529/185660540-1a6b4d9f-6224-4f33-b5c9-5e127742940f.png)
It seems to be coming from the `.svelte-kit` folder that is generated at runtime.

Also if you take a look at the `ambient.d.ts` file inside of `/node_modules/@sveltejs/kit/types/ambient.d.ts` you can see the following conflict there as well. 
![image](https://user-images.githubusercontent.com/75957529/185660799-f1a48374-cf1d-442b-a62a-b8dc4de162f2.png)

**Comment by bfanger** [comment]
The vite.config.ts is not part of the includes, i've created a fix https://github.com/sveltejs/kit/pull/6140 upstream.

As a workaround you could add:
```json,
  "include": [
    "./src/app.d.ts",
    "./src/**/*.js",
    "./src/**/*.ts",
    "./src/**/*.svelte",
    "./tests/**/*.js",
    "./tests/**/*.ts",
    "./tests/**/*.svelte",
    "./vite.config.ts"
  ]
  ```
to the `/tsconfig.json`

**Comment by Fractal-Tess** [comment]
> The vite.config.ts is not part of the includes, i've created a fix https://github.com/sveltejs/kit/pull/6140 upstream.
> 
> As a workaround you could add:
> ```json,
>   "include": [
>     "./src/app.d.ts",
>     "./src/**/*.js",
>     "./src/**/*.ts",
>     "./src/**/*.svelte",
>     "./tests/**/*.js",
>     "./tests/**/*.ts",
>     "./tests/**/*.svelte",
>     "./vite.config.ts"
>   ]
>   ```
> to the `/tsconfig.json`

Thank you!
